Feat/6 music list
taodemy/taotify pull request #40
Opened 2023-04-08 12:41 UTC by HarryuCATGREY

### Descriptions
Use the player component we have created to play the music by clicking the name on the list shown on the index page. 
- Link to UI design (if possible):

### Provide screenshots or videos that the function is working.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/70834897/230721520-c2be3d66-d971-4399-9b7c-c59c437e8555.png">

### Provide screenshots of no warning, or error in the console.
<img width="586" alt="image" src="https://user-images.githubusercontent.com/70834897/230721534-ab99d3d2-9c49-407c-b7dd-fde4bd074160.png">
The context test will be completed in another card
- [x] All unit tests passing and coverage of testing is more than 90% unless special needs.
- [x] No merge conflict with the `main` branch, make sure your code is up to date with `main`.
- [x] Check PR title is aligned with your ticket.
- [x] Check your app will run without crashes.
- [x] Check if there are hard-coded values.
- [x] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [x] Check you are using `camelCase && PascalCase` correctly.
- [x] Remove unused comments.

2023-04-08 14:48 UTC, RedRe4per requested changes

2023-04-08 14:48 UTC, RedRe4per commented on src/pages/index.tsx
> +  const urls = await Promise.all(
It is necessary to consider the rejected situation in the child promises. Try promise.allsettled().

2023-04-08 14:48 UTC, RedRe4per commented on src/pages/index.tsx
> +  for (let i = 0; i < newSongs.length; i++) {
A more concise way can be used.
urls.forEach((url, index) => {
  if (url.status === 'fulfilled') newSongs[i].audioUrl = url.value;
});

2023-04-08 14:48 UTC, RedRe4per commented on src/layouts/MusicPlayer.tsx
> +  const context = useContext(MusicContext);
const { musicList, musicIndex } = useContext(MusicContext);
Reasonable use of destructuring assignment can make the code more readable.

2023-04-08 14:48 UTC, RedRe4per commented on src/contexts/MusicContext.tsx
> +  setMusicIndex: () => null,
Will it really return a null? Maybe what you're looking for is setMusicIndex: () => void ?

2023-04-08 14:48 UTC, RedRe4per commented on src/contexts/MusicContext.tsx
>    setMusicList: () => null,
Same to line 14

2023-04-08 14:48 UTC, RedRe4per commented on src/components/MusicList.tsx
> +  const context = useContext(MusicContext);
const {setMusicList, setMusicIndex} = useContext(MusicContext);

2023-04-09 01:55 UTC, Double-Twelve commented on __tests__/components/MusicList.test.jsx
> +  // });
remove it if not in use

2023-04-09 01:55 UTC, Double-Twelve commented on package.json
> +    "react-test-renderer": "^18.2.0",
where is this library used?

2023-04-09 01:55 UTC, Double-Twelve commented on __tests__/components/ListItem.test.tsx
> +};
remove it if not in use

2023-04-09 01:55 UTC, Double-Twelve commented on __tests__/components/ListItem.test.tsx
> +    );
use `<table>` and `<tbody>` to wrap `<ListItem>`, so you don't need to define `originalConsoleError`, and you don't need to use `beforeAll` and `afterAll`

2023-04-10 09:44 UTC, HarryuCATGREY commented on src/pages/index.tsx
> +  const urls = await Promise.all(
I am still not understanding, I will research on this topic

2023-04-10 09:45 UTC, HarryuCATGREY commented on src/pages/index.tsx
> +  for (let i = 0; i < newSongs.length; i++) {
Thanks, fixed.

2023-04-10 09:50 UTC, HarryuCATGREY commented on src/layouts/MusicPlayer.tsx
> +  const context = useContext(MusicContext);
Thank you, I have improved this point.

2023-04-10 09:56 UTC, HarryuCATGREY commented on src/contexts/MusicContext.tsx
> +  setMusicIndex: () => null,
Sure, I will change the code to setMusicIndex: () => {} for this default function.

2023-04-10 09:58 UTC, HarryuCATGREY commented on src/contexts/MusicContext.tsx
>    setMusicList: () => null,
OK, I have fixed it.

2023-04-10 09:59 UTC, HarryuCATGREY commented on src/components/MusicList.tsx
> +  const context = useContext(MusicContext);
Thanks, fixed

2023-04-10 10:02 UTC, HarryuCATGREY commented on src/pages/index.tsx
> +  return { props: { newSongs }, revalidate: 600 };
Understand, thanks.

2023-04-10 10:02 UTC, HarryuCATGREY commented on src/components/MusicList.tsx
> +import React, { useContext, useEffect, useState } from "react";
I have deleted them, thanks

2023-04-10 10:03 UTC, HarryuCATGREY commented on __tests__/components/MusicList.test.jsx
> +  // });
Sure

2023-04-10 10:06 UTC, HarryuCATGREY commented on package.json
> +    "react-test-renderer": "^18.2.0",
I had used it in test music list component, but then I find a better way to test, I should remove this dependency.

2023-04-10 10:07 UTC, HarryuCATGREY commented on __tests__/components/ListItem.test.tsx
> +};
Sure, thanks

2023-04-10 10:08 UTC, HarryuCATGREY commented on __tests__/components/ListItem.test.tsx
> +    );
Thanks, I have fixed them.

2023-04-11 02:26 UTC, tatoMa reviewed
Why there are soooooo many irrelevant files format changed?

2023-04-11 02:26 UTC, tatoMa commented on src/components/MusicList.tsx
> +          <ListItem key={i} music={e} index={i} loadMusicList={loadMusicList} />
So ListItem is an individual component mapped from the list. When a user clicks ListItem, fires the loadMusicList function, and triggers the loadMusicList function, it sets the whole music list every time in this function.

Emmmm, maybe something is not right.

2023-04-11 02:26 UTC, tatoMa commented on src/layouts/MusicPlayer.tsx
> +  const handleEnd = () => {
When you think you need to write a comment to explain this simple function, you can improve it by giving it a proper name.

2023-04-11 10:03 UTC, HarryuCATGREY commented
> Why there are soooooo many irrelevant files format changed?

I think it is caused by prettier.

2023-04-11 10:07 UTC, HarryuCATGREY commented on src/layouts/MusicPlayer.tsx
> +  const handleEnd = () => {
OK, understand, we will improve that. The reason why we use these comments is because we want to help the people who will make the player component can better understand our code for their future design.

2023-04-11 10:17 UTC, HarryuCATGREY commented on src/components/MusicList.tsx
> +          <ListItem key={i} music={e} index={i} loadMusicList={loadMusicList} />
So should I add an addMusic function in /src/contexts/MusicContext.tsx?

2023-04-14 12:13 UTC, Double-Twelve commented on package.json
> +    "@types/next-auth": "^3.15.0",
why do you add it?

2023-04-14 12:53 UTC, HarryuCATGREY commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "src/pages/_middleware.js"],
Sorry, because of my git problem, I uploaded the code of other projects here, I will correct this, thank you for you check~

2023-04-14 12:53 UTC, HarryuCATGREY commented on package.json
> +    "@types/next-auth": "^3.15.0",
Sorry, because of my git problem, I uploaded the code of other projects here, I will correct this, thank you for you check~

2023-04-15 11:10 UTC, Double-Twelve approved these changes

2023-04-15 13:02 UTC, RedRe4per approved these changes

2023-04-15 13:13 UTC, merged