Feature/9 music component volume slide controller
taodemy/taotify pull request #41
Opened 2023-04-10 05:52 UTC by Prom1s1ngYoung

### Descriptions
You can drag the volume slide using the thumb, and you can also click the other place inside the slide to quickly update the volume level.
Why extract calculateVolume function?
For testing logic, we need to mock this return value. Since the jest and tailwind have different CSS frameworks, you can easily check that the slide will have 0 width and 0 height in jest, so we cannot just test drag and click operations according to UI.

- Link to UI design (if possible):

### Provide screenshots or videos that the function is working.
https://user-images.githubusercontent.com/110534329/230834684-4efed6ae-da33-4037-a383-af67bdf0e8e9.mov

### Provide screenshots of no warning, or error in the console.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/110534329/230834751-bb5d85ef-b6c3-415f-af92-a62639a33351.png">

- [x] All unit tests passing and coverage of testing is more than 90% unless special needs.
- [x] No merge conflict with the `main` branch, make sure your code is up to date with `main`.
- [x] Check PR title is aligned with your ticket.
- [x] Check your app will run without crashes.
- [x] Check if there are hard-coded values.
- [x] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [x] Check you are using `camelCase && PascalCase` correctly.
- [x] Remove unused comments.

2023-04-10 13:52 UTC, RedRe4per requested changes
I'm not sure if my question necessarily needs to be revised? Because there is no detailed description in this card. But generally speaking, a muted icon is a must.

2023-04-10 13:52 UTC, RedRe4per commented on src/components/VolumeSlideController.tsx
> +export default function VolumeSlideController() {
It seems that the audio element is not passed into the component as a ref or parameter. How does this component control the volume if there is no audio element?

2023-04-10 13:52 UTC, RedRe4per commented on src/components/VolumeSlideController.tsx
> +    <div className={`w-52 absolute right-10 bottom-5 mx-auto`} data-testid="volumeSlideContainer">
In zenhub "Update music component with volume controller#9": In addition to the slider, we also need an additional music icon to directly control the muted state by clicking. There is no such part in the code.

2023-04-11 04:31 UTC, Prom1s1ngYoung commented on src/components/VolumeSlideController.tsx
> +export default function VolumeSlideController() {
I will create another enhancement card to do this, since this card already contained several features above the card requirments.

2023-04-11 04:34 UTC, Prom1s1ngYoung commented on src/components/VolumeSlideController.tsx
> +    <div className={`w-52 absolute right-10 bottom-5 mx-auto`} data-testid="volumeSlideContainer">
You are right, I will update it.

2023-04-11 04:36 UTC, Prom1s1ngYoung commented on src/components/VolumeSlideController.tsx
> +    <div className={`w-52 absolute right-10 bottom-5 mx-auto`} data-testid="volumeSlideContainer">
So I have designed a volume context that will share the several data for all volume related components, the volume will be easily controlled when updating it, so I will implement this feature in another card.

2023-04-12 06:30 UTC, tatoMa reviewed
The event handler of this slider is not perfect. Please refer to the recorded video I have sent to you.

2023-04-14 13:23 UTC, RedRe4per approved these changes
LGTM

2023-04-15 02:13 UTC, Trent1900 approved these changes
LGTM

2023-04-19 06:59 UTC, merged